version: "3.9"

services:
  # =================================================================
  # 1. REDIS NỘI BỘ DÀNH RIÊNG CHO LIVEKIT (BẢO MẬT, KHÔNG MỞ PORT)
  # =================================================================
  redis-livekit:
    image: redis:7-alpine
    command: redis-server --requirepass "fE0RUoc9Y7vvUReP2bgoNgN7mwYMZ3fILM1vRGLo1kzwJOKOLT5V0ovdY3jY8v8c"
    restart: unless-stopped
    volumes:
      - redis-livekit-data:/data

  # =================================================================
  # 2. LÕI TRUYỀN TẢI VIDEO (LIVEKIT SERVER)
  # =================================================================
  livekit-server:
    image: livekit/livekit-server:latest
    depends_on:
      - redis-livekit
    environment:
      LIVEKIT_KEYS: "API_nextgen_admin_key: SEC_thanhnguyen_group_super_secure_9999"
      LIVEKIT_CONFIG: |
        port: 7880
        rtc:
          tcp_port: 7881
          port_range_start: 50000
          port_range_end: 50200
          use_external_ip: true
        redis:
          # Trỏ trực tiếp vào tên container Redis nội bộ ở trên
          address: "redis-livekit:6379"
          password: "fE0RUoc9Y7vvUReP2bgoNgN7mwYMZ3fILM1vRGLo1kzwJOKOLT5V0ovdY3jY8v8c"
          db: 0
    ports:
      - "7880:7880"
      - "7881:7881"
      - "50000-50200:50000-50200/udp"
    deploy:
      resources:
        limits:
          memory: 1G
    restart: unless-stopped

# Khai báo ổ cứng ảo để lưu dữ liệu Redis không bị mất khi restart
volumes:
  redis-livekit-data:
